name: "Todos"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO-2-GH-Issue"
        uses: "jamminroot/todo-2-gh-issue@master"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
